---
- name: set download location on master for tar file
  set_fact:
    ncbi_blast_download_folder: "{{ ansible_env.PWD ~ '/downloads' }}"
  delegate_to: local
  run_once: true

- name: create downloads folder if it does not exist yet
  file:
    dest: "{{ ncbi_blast_download_folder }}"
    state: directory
  tags: ncbi_blast_master_download

- name: Download ncbi blast to ansible-master if we don't have it
  local_action: get_url \
    url="{{ ncbi_blast_download_url }}" \
    dest="{{ ncbi_blast_download_folder ~ '/' ~ ncbi_blast_file_tar }}" \
    force=no
  run_once: true
  tags: ncbi_blast_master_download
