---
- include: set_vars.yml

- include: download_to_master.yml
  when: ncbi_blast_download_folder_remote is undefined 

- include: download_to_remote.yml
  when: ncbi_blast_download_folder_remote is defined

- name: Create install directory
  file:
    dest: "{{ ncbi_blast_install_dir }}"
    state: directory
  tags: [ncbi_blast]

- name: set name of unpacked ncbi blast directory
  set_fact:
    ncbi_blast_unpack_dir: "{{ ncbi_blast_install_dir ~ '/ncbi_blast' }}"

- name: unpack archive from master
  unarchive:
    copy:    "{{ (ncbi_blast_download_folder_remote is defined) | ternary('no','yes') }}"
    src:     "{{ ncbi_blast_download_folder ~ '/' ~ ncbi_blast_file_tar }}"
    dest:    "{{ ncbi_blast_install_dir }}"
    creates: "{{ ncbi_blast_ini_path }}"
  tags: [ncbi_blast]
